[build]
  base    = "Athar/beta"
  publish = "Athar/beta"
  command = ""
[functions]
  directory    = "Athar/beta/netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = [
    "@supabase/supabase-js",
    "jwks-rsa",
    "jsonwebtoken",
    "nodemailer",
    "@google/generative-ai"
  ]
[build.environment]
  NODE_VERSION = "18"
